import { createContext, useContext } from 'react';

export type Language = 'en' | 'ta' | 'hi' | 'ml' | 'te' | 'kn';

export const LANGUAGES: Language[] = ['en', 'ta', 'hi', 'ml', 'te', 'kn'];

export const LANGUAGE_LABELS: Record<Language, string> = {
  en: 'English',
  ta: 'தமிழ்',
  hi: 'हिन्दी',
  ml: 'മലയാളം',
  te: 'తెలుగు',
  kn: 'ಕನ್ನಡ'
};

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    brandName: 'IGO PROTEIN CUTS',
    tagline: 'Farm-Fresh, Antibiotic-Free Protein',
    taglineSub: 'Delivered in 30-90 Minutes',
    ecosystem: 'IGO ECOSYSTEM',
    adminPortal: 'Admin Portal',
    deliverTo: 'Deliver to',
    searchPlaceholder: 'Search cuts, recipes or ask AI...',
    cart: 'CART',
    account: 'Account',
    member: 'Member',
    expressActive: 'EXPRESS 30-90 MIN DELIVERY ACTIVE',
    orderFreshCuts: 'Order Fresh Cuts Now',
    exploreGymPlans: 'Explore Gym Protein Plans',
    ordersToday: 'Orders Delivered Today',
    coldChain: 'Strict Cold Chain',
    verifiedReviews: '10,000+ Verified Reviews',
    exploreCategories: 'Fresh Protein Master Catalog',
    viewAll: 'View All',
    flashDeals: "Today's Flash Meat Deals",
    mostPopular: 'Best Sellers Loved by Chefs & Athletes',
    farmToHomeTitle: 'The IGO Farm-To-Home Cold Chain',
    farmToHomeSub: 'We never freeze our fresh cuts. Kept in 0-4°C chillers continuously.',
    signatureRecipes: 'Signature Meat Recipes',
    exploreRecipes: 'Explore All Recipes',
    subscriptionsTitle: 'Protein Cuts Subscriptions',
    activateSub: 'Activate Subscription',
    proteinCalc: 'Protein Intake Calculator',
    calcSub: 'Calculate your daily macro protein target & get personalized meat recommendations',
    calcBtn: 'Calculate Protein Needs',
    igoFamily: 'IGO Ecosystem Family',
    igoFamilySub: 'Explore our integrated agro, cold-chain, fisheries, and express delivery groups',
    // Footer
    footerTagline: 'Farm Fresh, Stay Healthy',
    customerCare: 'Customer Care',
    termsConditions: 'Terms & Conditions',
    privacyPolicy: 'Privacy Policy',
    shippingPolicy: 'Shipping Policy',
    returnPolicy: 'Return Policy',
    contactUs: 'Contact us',
    accountHeading: 'Account',
    myAccount: 'My Account',
    cartNav: 'Cart',
    wishlist: 'Wishlist',
    productNav: 'Product',
    blog: 'Blog',
    newsletter: 'News Letter',
    subscribedMsg: 'Subscribed! Watch your inbox.',
    emailPlaceholder: 'Email',
    subscribe: 'Subscribe',
    followUs: 'Follow Us',
    copyright: 'IGO Protein Cuts. All rights reserved.',
    fssaiLic: 'FSSAI Lic: 10022043000918',
    // Breadcrumbs & common
    home: 'Home',
    addToCart: 'Add',
    soldOut: 'Sold Out',
    deliveryIn: 'Delivery in',
    deliveryTime30to90: 'Delivery in 30-90 mins',
    buyNow: 'Buy Now',
    added: 'Added!',
    notify: 'Notify',
    notified: 'Notified!',
    addToBasket: 'Add to Basket',
    outOfStockBanner: 'Currently Out of Stock',
    outOfStockBannerSub: "We're restocking this — leave your email and we'll let you know the moment it's back.",
    notifyMeCta: 'Notify Me',
    notifyMeSub: 'when back in stock',
    requestAccepted: 'Request Accepted',
    requestAcceptedSub: "We'll notify you when this product becomes available.",
    notifySubmit: 'Notify Me',
    notifySubmitting: 'Submitting...',
    notifyCancel: 'Cancel',
    notifyErrorGeneric: "Couldn't submit your request — please try again in a moment.",
    close: 'Close',
    // Cart page — step labels, header, empty state, order confirmation
    stepYourCart: 'Your Cart',
    stepDeliveryPayment: 'Delivery & Payment',
    stepCookingPlan: 'Cooking Plan',
    stepConfirmed: 'Confirmed',
    continueShopping: 'Continue Shopping',
    yourCartTitle: 'Your Cart',
    itemsReady: 'ready for delivery',
    clearCart: 'Clear Cart',
    emptyCartTitle: 'Your cart is currently empty',
    emptyCartSub: 'Explore farm-fresh, 100% antibiotic-free chicken cuts, tender mutton, wild-caught seafood, and fresh farm eggs.',
    shopFreshChicken: 'Shop Fresh Chicken',
    viewHotOffers: 'View Hot Offers',
    orderPlacedTitle: 'Order Placed Successfully!',
    orderPlacedSub: 'Your cold-chain order is confirmed and being prepared by our master butchers.',
    yourOrderNumber: 'Your Order Number',
    orderSummary: 'Order Summary',
    totalPaid: 'Total Paid',
    deliverySlotLabel: 'Delivery slot',
    trackThisOrder: 'Track This Order',
    viewInMyOrders: 'View in My Orders',
    orderSavedNote: 'This order is now saved to your account and will always be visible under My Orders in your Profile.',
    // Cart Step 2 — address, delivery slot, payment
    deliverToStep: 'Deliver To',
    noSavedAddress: 'No saved address found.',
    addOneInProfile: 'Add one in your Profile',
    toContinue: 'to continue.',
    defaultLabel: 'Default',
    changeLabel: 'Change',
    editLabel: 'Edit',
    addNewAddress: 'Add a new address',
    selectDeliverySlot: 'Select Delivery Time Slot',
    coldChainGuaranteed: 'Cold Chain Guaranteed',
    slotExpress: '30-Min Express',
    slotInstantDispatch: 'Instant Dispatch',
    slotMorning: 'Morning',
    slotAfternoon: 'Afternoon',
    slotEvening: 'Evening',
    selectPaymentMethod: 'Select Payment Method',
    secure256bit: '256-bit Secure',
    paymentCard: 'Card',
    paymentWallet: 'Wallet',
    paymentCOD: 'Cash on Delivery',
    redeemWalletPrefix: 'Also redeem up to ₹',
    redeemWalletSuffix: ' IGO Wallet credit on this order',
    // Cart Step 3 — cooking plan
    cookingPlanQuestion: 'What are you planning to cook?',
    cookingPlanSub: "Pick a cooking style and we'll match fresh vegetables and masalas to go with your order.",
    cookBiryani: 'Biryani',
    cookCurry: 'Curry / Gravy',
    cookFry: 'Fry / Roast',
    cookKebab: 'Kebab / Tandoori',
    // Frequently bought together
    frequentlyBought: 'Frequently Bought Together',
    frequentlyBoughtSub: 'Complete your kitchen order with fresh protein additions.',
    addShort: '+ Add',
    bulkDiscountPrefix: 'Bulk -',
    removeLabel: 'Remove',
    // Order summary sidebar
    itemsTotal: 'Items Total',
    bulkWholesaleDiscount: 'Bulk / Wholesale Discount',
    vacuumPacking: '0-4°C Vacuum Gel Pack Packing',
    freeLabel: 'FREE',
    expressDeliveryFee: 'Express Delivery Fee',
    taxesGST: 'Taxes & GST',
    promoCoupon: 'Promo Coupon',
    walletPointsLabel: 'IGO Wallet Points',
    appliedLabel: 'applied',
    searchOffersPlaceholder: 'Search offers or enter a code',
    applyBtn: 'Apply',
    availableOffers: 'Available Offers',
    totalSavingsPrefix: 'Total Savings on this order: ₹',
    grandPayableTotal: 'Grand Payable Total',
    includesTaxes: 'Includes all applicable Taxes & GST',
    continueToDelivery: 'Continue to Delivery & Payment',
    continueToCooking: 'Continue to Cooking Plan',
    placeOrderBtn: 'Place Order',
    placingOrder: 'Placing Order...',
    // Simulated payment modal
    payViaLabel: 'Pay via',
    paymentSimNote: "Live payment gateway isn't connected yet — this confirms your order as a demo payment. No real money is charged.",
    amountLabel: 'Amount',
    cancelBtn: 'Cancel',
    confirmPayment: 'Confirm Payment',
  },
  ta: {
    brandName: 'IGO புரோட்டீன் கட்ஸ்',
    tagline: 'பண்ணை நன்னீர் & ஆர்கானிக் புரதம்',
    taglineSub: '30-90 நிமிடங்களில் உங்கள் இல்லத்தில்',
    ecosystem: 'IGO ஈகோசிஸ்டம்',
    adminPortal: 'நிர்வாகி போர்ட்டல்',
    deliverTo: 'டெலிவரி இடம்',
    searchPlaceholder: 'கட்ஸ், சமையல் குறிப்புகள் தேடுங்கள்...',
    cart: 'கார்ட்',
    account: 'கணக்கு',
    member: 'உறுப்பினர்',
    expressActive: '30-90 நிமிட விரைவு டெலிவரி இயங்குகிறது',
    orderFreshCuts: 'இப்பொழுதே ஆர்டர் செய்க',
    exploreGymPlans: 'ஜிம் புரோட்டீன் திட்டங்கள்',
    ordersToday: 'இன்று டெலிவரி செய்யப்பட்டவை',
    coldChain: '0-4°C சளி சங்கிலி',
    verifiedReviews: '10,000+ சான்றளிக்கப்பட்ட மதிப்புரைகள்',
    exploreCategories: 'புதிய புரதப் பொருட்கள் வரிசை',
    viewAll: 'அனைத்தையும் காண்க',
    flashDeals: 'இன்றைய சிறப்பு தள்ளுபடி சலுகைகள்',
    mostPopular: 'அதிகம் விரும்பப்படும் புதிய கட்ஸ்',
    farmToHomeTitle: 'IGO பண்ணையிலிருந்து வீடு வரை குளிர் சங்கிலி',
    farmToHomeSub: 'நாங்கள் ஒருபோதும் இறைச்சியை உறைவிப்பதில்லை. 0-4°C குளிர்ச்சியில் பாதுகாக்கப்படுகிறது.',
    signatureRecipes: 'பிரத்யேக இறைச்சி சமையல் குறிப்புகள்',
    exploreRecipes: 'அனைத்து சமையல் குறிப்புகள்',
    subscriptionsTitle: 'புரோட்டீன் கட்ஸ் சந்தா திட்டங்கள்',
    activateSub: 'சந்தாவைத் தொடங்குங்கள்',
    proteinCalc: 'புரதத் தேவை கணக்கீடு',
    calcSub: 'உங்கள் தினசரி புரத இலக்கைக் கணக்கிட்டு பரிந்துரைக்கப்படும் கட்ஸ்களைப் பெறுங்கள்',
    calcBtn: 'புரதத் தேவையைத் தெரிந்துகொள்க',
    igoFamily: 'IGO குழுமத்தின் துணை நிறுவனங்கள்',
    igoFamilySub: 'பண்ணை, குளிர் சங்கிலி, மீன்வளம் மற்றும் விரைவு விநியோக சேவைகளை ஆராயுங்கள்',
    // Footer
    footerTagline: 'பண்ணை நன்னீர், ஆரோக்கியமாக இருங்கள்',
    customerCare: 'வாடிக்கையாளர் சேவை',
    termsConditions: 'விதிமுறைகள் & நிபந்தனைகள்',
    privacyPolicy: 'தனியுரிமைக் கொள்கை',
    shippingPolicy: 'டெலிவரி கொள்கை',
    returnPolicy: 'திரும்பப்பெறும் கொள்கை',
    contactUs: 'எங்களை தொடர்பு கொள்ள',
    accountHeading: 'கணக்கு',
    myAccount: 'எனது கணக்கு',
    cartNav: 'கார்ட்',
    wishlist: 'விருப்பப் பட்டியல்',
    productNav: 'பொருட்கள்',
    blog: 'வலைப்பதிவு',
    newsletter: 'செய்திமடல்',
    subscribedMsg: 'சந்தா செய்யப்பட்டது! உங்கள் இன்பாக்ஸைப் பாருங்கள்.',
    emailPlaceholder: 'மின்னஞ்சல்',
    subscribe: 'சந்தா செய்யுங்கள்',
    followUs: 'எங்களைப் பின்தொடருங்கள்',
    copyright: 'IGO புரோட்டீன் கட்ஸ். அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
    fssaiLic: 'FSSAI உரிமம்: 10022043000918',
    // Breadcrumbs & common
    home: 'முகப்பு',
    addToCart: 'சேர்',
    soldOut: 'கையிருப்பில் இல்லை',
    deliveryIn: 'டெலிவரி',
    deliveryTime30to90: '30-90 நிமிடங்களில் டெலிவரி',
    buyNow: 'இப்போது வாங்குங்கள்',
    added: 'சேர்க்கப்பட்டது!',
    notify: 'அறிவிக்கவும்',
    notified: 'அறிவிக்கப்பட்டது!',
    addToBasket: 'கூடையில் சேர்',
    outOfStockBanner: 'தற்போது கையிருப்பில் இல்லை',
    outOfStockBannerSub: 'நாங்கள் மீண்டும் நிரப்புகிறோம் — உங்கள் மின்னஞ்சலைக் கொடுங்கள், கிடைத்தவுடன் தெரிவிக்கிறோம்.',
    notifyMeCta: 'எனக்கு தெரிவிக்கவும்',
    notifyMeSub: 'கையிருப்பில் வரும்போது',
    requestAccepted: 'கோரிக்கை ஏற்கப்பட்டது',
    requestAcceptedSub: 'இந்த பொருள் கிடைக்கும்போது உங்களுக்கு தெரிவிப்போம்.',
    notifySubmit: 'எனக்கு தெரிவிக்கவும்',
    notifySubmitting: 'சமர்ப்பிக்கிறது...',
    notifyCancel: 'ரத்து செய்',
    notifyErrorGeneric: 'கோரிக்கையை சமர்ப்பிக்க முடியவில்லை — சிறிது நேரம் கழித்து முயற்சிக்கவும்.',
    close: 'மூடு',
    stepYourCart: 'உங்கள் கார்ட்',
    stepDeliveryPayment: 'டெலிவரி & பணம்',
    stepCookingPlan: 'சமையல் திட்டம்',
    stepConfirmed: 'உறுதி செய்யப்பட்டது',
    continueShopping: 'தொடர்ந்து ஷாப்பிங் செய்யுங்கள்',
    yourCartTitle: 'உங்கள் கார்ட்',
    itemsReady: 'டெலிவரிக்கு தயார்',
    clearCart: 'கார்ட்டை காலி செய்',
    emptyCartTitle: 'உங்கள் கார்ட் தற்போது காலியாக உள்ளது',
    emptyCartSub: 'பண்ணை நன்னீர், 100% ஆன்டிபயாடிக் இல்லாத கோழி துண்டுகள், மென்மையான ஆட்டிறைச்சி, கடல் இறால் மற்றும் புதிய பண்ணை முட்டைகளை ஆராயுங்கள்.',
    shopFreshChicken: 'புதிய கோழி வாங்குங்கள்',
    viewHotOffers: 'சிறப்பு சலுகைகளை காண்க',
    orderPlacedTitle: 'ஆர்டர் வெற்றிகரமாக வைக்கப்பட்டது!',
    orderPlacedSub: 'உங்கள் குளிர் சங்கிலி ஆர்டர் உறுதி செய்யப்பட்டு எங்கள் முதன்மை கசாப்புக்காரர்களால் தயாரிக்கப்படுகிறது.',
    yourOrderNumber: 'உங்கள் ஆர்டர் எண்',
    orderSummary: 'ஆர்டர் சுருக்கம்',
    totalPaid: 'மொத்தம் செலுத்தியது',
    deliverySlotLabel: 'டெலிவரி நேரம்',
    trackThisOrder: 'இந்த ஆர்டரை கண்காணிக்க',
    viewInMyOrders: 'எனது ஆர்டர்களில் காண்க',
    orderSavedNote: 'இந்த ஆர்டர் இப்போது உங்கள் கணக்கில் சேமிக்கப்பட்டுள்ளது, மேலும் உங்கள் சுயவிவரத்தில் எனது ஆர்டர்களின் கீழ் எப்போதும் காணக்கூடியதாக இருக்கும்.',
    // Cart Step 2 — address, delivery slot, payment
    deliverToStep: 'விநியோக முகவரி',
    noSavedAddress: 'சேமிக்கப்பட்ட முகவரி இல்லை.',
    addOneInProfile: 'உங்கள் சுயவிவரத்தில் ஒன்றைச் சேர்க்கவும்',
    toContinue: 'தொடர.',
    defaultLabel: 'இயல்புநிலை',
    changeLabel: 'மாற்று',
    editLabel: 'திருத்து',
    addNewAddress: 'புதிய முகவரி சேர்க்க',
    selectDeliverySlot: 'டெலிவரி நேரத்தைத் தேர்ந்தெடுக்கவும்',
    coldChainGuaranteed: 'குளிர் சங்கிலி உத்தரவாதம்',
    slotExpress: '30-நிமிட எக்ஸ்பிரஸ்',
    slotInstantDispatch: 'உடனடி அனுப்புதல்',
    slotMorning: 'காலை',
    slotAfternoon: 'மதியம்',
    slotEvening: 'மாலை',
    selectPaymentMethod: 'பணம் செலுத்தும் முறையைத் தேர்ந்தெடுக்கவும்',
    secure256bit: '256-பிட் பாதுகாப்பு',
    paymentCard: 'கார்டு',
    paymentWallet: 'வாலட்',
    paymentCOD: 'டெலிவரியின் போது பணம்',
    redeemWalletPrefix: 'இந்த ஆர்டரில் ₹',
    redeemWalletSuffix: ' வரை IGO வாலட் கிரெடிட்டைப் பயன்படுத்தவும்',
    // Cart Step 3 — cooking plan
    cookingPlanQuestion: 'நீங்கள் என்ன சமைக்க திட்டமிடுகிறீர்கள்?',
    cookingPlanSub: 'ஒரு சமையல் பாணியைத் தேர்ந்தெடுக்கவும், உங்கள் ஆர்டருக்கு ஏற்ற காய்கறிகள் மற்றும் மசாலாக்களை நாங்கள் பொருத்துவோம்.',
    cookBiryani: 'பிரியாணி',
    cookCurry: 'கறி / குழம்பு',
    cookFry: 'வறுவல் / ரோஸ்ட்',
    cookKebab: 'கபாப் / தந்தூரி',
    // Frequently bought together
    frequentlyBought: 'அடிக்கடி ஒன்றாக வாங்கப்படுபவை',
    frequentlyBoughtSub: 'புதிய புரத பொருட்களுடன் உங்கள் சமையலறை ஆர்டரை முழுமையாக்குங்கள்.',
    addShort: '+ சேர்',
    bulkDiscountPrefix: 'மொத்த -',
    removeLabel: 'நீக்கு',
    // Order summary sidebar
    itemsTotal: 'பொருட்களின் மொத்தம்',
    bulkWholesaleDiscount: 'மொத்த / டோக்கு தள்ளுபடி',
    vacuumPacking: '0-4°C வெற்றிட ஜெல் பேக் பேக்கிங்',
    freeLabel: 'இலவசம்',
    expressDeliveryFee: 'எக்ஸ்பிரஸ் டெலிவரி கட்டணம்',
    taxesGST: 'வரிகள் & GST',
    promoCoupon: 'ப்ரோமோ கூப்பன்',
    walletPointsLabel: 'IGO வாலட் பாயிண்ட்ஸ்',
    appliedLabel: 'பயன்படுத்தப்பட்டது',
    searchOffersPlaceholder: 'சலுகைகளைத் தேடு அல்லது குறியீட்டை உள்ளிடவும்',
    applyBtn: 'பயன்படுத்து',
    availableOffers: 'கிடைக்கும் சலுகைகள்',
    totalSavingsPrefix: 'இந்த ஆர்டரில் மொத்த சேமிப்பு: ₹',
    grandPayableTotal: 'செலுத்த வேண்டிய மொத்தத் தொகை',
    includesTaxes: 'அனைத்து பொருந்தக்கூடிய வரிகள் & GST அடங்கும்',
    continueToDelivery: 'டெலிவரி & பணம் செலுத்த தொடரவும்',
    continueToCooking: 'சமையல் திட்டத்திற்கு தொடரவும்',
    placeOrderBtn: 'ஆர்டர் செய்க',
    placingOrder: 'ஆர்டர் செய்யப்படுகிறது...',
    // Simulated payment modal
    payViaLabel: 'மூலம் செலுத்துங்கள்',
    paymentSimNote: 'நேரடி பேமெண்ட் கேட்வே இன்னும் இணைக்கப்படவில்லை — இது உங்கள் ஆர்டரை டெமோ பேமெண்டாக உறுதிப்படுத்துகிறது. உண்மையான பணம் வசூலிக்கப்படாது.',
    amountLabel: 'தொகை',
    cancelBtn: 'ரத்து செய்',
    confirmPayment: 'பணம் செலுத்துவதை உறுதிப்படுத்து',
  },
  hi: {
    brandName: 'IGO प्रोटीन कट्स',
    tagline: 'फार्म-फ्रेश, एंटीबायोटिक-मुक्त प्रोटीन',
    taglineSub: '30-90 मिनट में डिलीवर',
    ecosystem: 'IGO इकोसिस्टम',
    adminPortal: 'एडमिन पोर्टल',
    deliverTo: 'डिलीवरी पता',
    searchPlaceholder: 'कट्स, रेसिपी खोजें या AI से पूछें...',
    cart: 'कार्ट',
    account: 'खाता',
    member: 'सदस्य',
    expressActive: 'एक्सप्रेस 30-90 मिनट डिलीवरी सक्रिय',
    orderFreshCuts: 'अभी ताज़ा कट्स ऑर्डर करें',
    exploreGymPlans: 'जिम प्रोटीन प्लान देखें',
    ordersToday: 'आज डिलीवर किए गए ऑर्डर',
    coldChain: 'सख्त कोल्ड चेन',
    verifiedReviews: '10,000+ सत्यापित समीक्षाएं',
    exploreCategories: 'ताज़ा प्रोटीन मास्टर कैटलॉग',
    viewAll: 'सभी देखें',
    flashDeals: 'आज के फ्लैश मीट डील्स',
    mostPopular: 'शेफ और एथलीटों की पसंदीदा बेस्ट सेलर्स',
    farmToHomeTitle: 'IGO फार्म-टू-होम कोल्ड चेन',
    farmToHomeSub: 'हम अपने ताज़ा कट्स को कभी फ्रीज़ नहीं करते। लगातार 0-4°C चिलर में रखा जाता है।',
    signatureRecipes: 'सिग्नेचर मीट रेसिपी',
    exploreRecipes: 'सभी रेसिपी देखें',
    subscriptionsTitle: 'प्रोटीन कट्स सब्सक्रिप्शन',
    activateSub: 'सब्सक्रिप्शन शुरू करें',
    proteinCalc: 'प्रोटीन इनटेक कैलकुलेटर',
    calcSub: 'अपना दैनिक मैक्रो प्रोटीन लक्ष्य गणना करें और व्यक्तिगत मीट सिफारिशें पाएं',
    calcBtn: 'प्रोटीन आवश्यकता जानें',
    igoFamily: 'IGO इकोसिस्टम परिवार',
    igoFamilySub: 'हमारे एकीकृत कृषि, कोल्ड-चेन, मत्स्य पालन और एक्सप्रेस डिलीवरी समूहों को जानें',
    // Footer
    footerTagline: 'फार्म फ्रेश, स्वस्थ रहें',
    customerCare: 'ग्राहक सेवा',
    termsConditions: 'नियम व शर्तें',
    privacyPolicy: 'गोपनीयता नीति',
    shippingPolicy: 'शिपिंग नीति',
    returnPolicy: 'वापसी नीति',
    contactUs: 'संपर्क करें',
    accountHeading: 'खाता',
    myAccount: 'मेरा खाता',
    cartNav: 'कार्ट',
    wishlist: 'विशलिस्ट',
    productNav: 'उत्पाद',
    blog: 'ब्लॉग',
    newsletter: 'न्यूज़लेटर',
    subscribedMsg: 'सब्सक्राइब हो गया! अपना इनबॉक्स देखें।',
    emailPlaceholder: 'ईमेल',
    subscribe: 'सब्सक्राइब करें',
    followUs: 'हमें फॉलो करें',
    copyright: 'IGO प्रोटीन कट्स. सर्वाधिकार सुरक्षित.',
    fssaiLic: 'FSSAI लाइसेंस: 10022043000918',
    // Breadcrumbs & common
    home: 'होम',
    addToCart: 'जोड़ें',
    soldOut: 'स्टॉक खत्म',
    deliveryIn: 'डिलीवरी',
    deliveryTime30to90: '30-90 मिनट में डिलीवरी',
    buyNow: 'अभी खरीदें',
    added: 'जोड़ा गया!',
    notify: 'सूचित करें',
    notified: 'सूचित किया गया!',
    addToBasket: 'बास्केट में जोड़ें',
    outOfStockBanner: 'फ़िलहाल स्टॉक में नहीं',
    outOfStockBannerSub: 'हम इसे फिर से स्टॉक कर रहे हैं — अपना ईमेल छोड़ें, वापस आते ही हम बताएंगे।',
    notifyMeCta: 'मुझे सूचित करें',
    notifyMeSub: 'स्टॉक में आने पर',
    requestAccepted: 'अनुरोध स्वीकृत',
    requestAcceptedSub: 'यह उत्पाद उपलब्ध होने पर हम आपको सूचित करेंगे।',
    notifySubmit: 'मुझे सूचित करें',
    notifySubmitting: 'सबमिट हो रहा है...',
    notifyCancel: 'रद्द करें',
    notifyErrorGeneric: 'आपका अनुरोध सबमिट नहीं हो सका — कृपया थोड़ी देर बाद पुनः प्रयास करें।',
    close: 'बंद करें',
    // Cart page — step labels, header, empty state, order confirmation
    stepYourCart: 'आपका कार्ट',
    stepDeliveryPayment: 'डिलीवरी व भुगतान',
    stepCookingPlan: 'कुकिंग प्लान',
    stepConfirmed: 'पुष्टि हो गई',
    continueShopping: 'शॉपिंग जारी रखें',
    yourCartTitle: 'आपका कार्ट',
    itemsReady: 'डिलीवरी के लिए तैयार',
    clearCart: 'कार्ट खाली करें',
    emptyCartTitle: 'आपका कार्ट फ़िलहाल खाली है',
    emptyCartSub: 'फार्म-फ्रेश, 100% एंटीबायोटिक-मुक्त चिकन कट्स, कोमल मटन, वाइल्ड-कॉट सीफूड और ताज़े फार्म अंडे देखें।',
    shopFreshChicken: 'ताज़ा चिकन खरीदें',
    viewHotOffers: 'हॉट ऑफर्स देखें',
    orderPlacedTitle: 'ऑर्डर सफलतापूर्वक दिया गया!',
    orderPlacedSub: 'आपका कोल्ड-चेन ऑर्डर पुष्ट हो गया है और हमारे मास्टर बुचर द्वारा तैयार किया जा रहा है।',
    yourOrderNumber: 'आपका ऑर्डर नंबर',
    orderSummary: 'ऑर्डर सारांश',
    totalPaid: 'कुल भुगतान',
    deliverySlotLabel: 'डिलीवरी स्लॉट',
    trackThisOrder: 'इस ऑर्डर को ट्रैक करें',
    viewInMyOrders: 'मेरे ऑर्डर में देखें',
    orderSavedNote: 'यह ऑर्डर अब आपके खाते में सेव कर दिया गया है और आपकी प्रोफाइल में मेरे ऑर्डर के तहत हमेशा दिखेगा।',
    // Cart Step 2 — address, delivery slot, payment
    deliverToStep: 'डिलीवरी पता',
    noSavedAddress: 'कोई सेव किया गया पता नहीं मिला।',
    addOneInProfile: 'अपनी प्रोफाइल में एक जोड़ें',
    toContinue: 'जारी रखने के लिए।',
    defaultLabel: 'डिफ़ॉल्ट',
    changeLabel: 'बदलें',
    editLabel: 'संपादित करें',
    addNewAddress: 'नया पता जोड़ें',
    selectDeliverySlot: 'डिलीवरी समय स्लॉट चुनें',
    coldChainGuaranteed: 'कोल्ड चेन गारंटीड',
    slotExpress: '30-मिनट एक्सप्रेस',
    slotInstantDispatch: 'तुरंत डिस्पैच',
    slotMorning: 'सुबह',
    slotAfternoon: 'दोपहर',
    slotEvening: 'शाम',
    selectPaymentMethod: 'भुगतान का तरीका चुनें',
    secure256bit: '256-बिट सुरक्षित',
    paymentCard: 'कार्ड',
    paymentWallet: 'वॉलेट',
    paymentCOD: 'डिलीवरी पर नकद भुगतान',
    redeemWalletPrefix: 'इस ऑर्डर पर ₹',
    redeemWalletSuffix: ' तक IGO वॉलेट क्रेडिट भी भुनाएं',
    // Cart Step 3 — cooking plan
    cookingPlanQuestion: 'आप क्या पकाने की योजना बना रहे हैं?',
    cookingPlanSub: 'एक कुकिंग स्टाइल चुनें और हम आपके ऑर्डर के साथ ताज़ी सब्ज़ियां और मसाले मिलाएंगे।',
    cookBiryani: 'बिरयानी',
    cookCurry: 'करी / ग्रेवी',
    cookFry: 'फ्राई / रोस्ट',
    cookKebab: 'कबाब / तंदूरी',
    // Frequently bought together
    frequentlyBought: 'अक्सर साथ खरीदे जाने वाले',
    frequentlyBoughtSub: 'ताज़ा प्रोटीन जोड़ के साथ अपना किचन ऑर्डर पूरा करें।',
    addShort: '+ जोड़ें',
    bulkDiscountPrefix: 'बल्क -',
    removeLabel: 'हटाएं',
    // Order summary sidebar
    itemsTotal: 'आइटम कुल',
    bulkWholesaleDiscount: 'बल्क / थोक छूट',
    vacuumPacking: '0-4°C वैक्यूम जेल पैक पैकिंग',
    freeLabel: 'मुफ़्त',
    expressDeliveryFee: 'एक्सप्रेस डिलीवरी शुल्क',
    taxesGST: 'कर व GST',
    promoCoupon: 'प्रोमो कूपन',
    walletPointsLabel: 'IGO वॉलेट पॉइंट्स',
    appliedLabel: 'लागू किया गया',
    searchOffersPlaceholder: 'ऑफर खोजें या कोड डालें',
    applyBtn: 'लागू करें',
    availableOffers: 'उपलब्ध ऑफर',
    totalSavingsPrefix: 'इस ऑर्डर पर कुल बचत: ₹',
    grandPayableTotal: 'कुल देय राशि',
    includesTaxes: 'सभी लागू कर व GST शामिल',
    continueToDelivery: 'डिलीवरी व भुगतान जारी रखें',
    continueToCooking: 'कुकिंग प्लान जारी रखें',
    placeOrderBtn: 'ऑर्डर करें',
    placingOrder: 'ऑर्डर किया जा रहा है...',
    // Simulated payment modal
    payViaLabel: 'भुगतान का माध्यम',
    paymentSimNote: 'लाइव पेमेंट गेटवे अभी कनेक्ट नहीं है — यह आपके ऑर्डर को डेमो पेमेंट के रूप में पुष्टि करता है। कोई वास्तविक पैसा नहीं लिया जाएगा।',
    amountLabel: 'राशि',
    cancelBtn: 'रद्द करें',
    confirmPayment: 'भुगतान की पुष्टि करें',
  },
  ml: {
    brandName: 'IGO പ്രോട്ടീൻ കട്സ്',
    tagline: 'ഫാം-ഫ്രഷ്, ആന്റിബയോട്ടിക് രഹിത പ്രോട്ടീൻ',
    taglineSub: '30-90 മിനിറ്റിനുള്ളിൽ ഡെലിവർ ചെയ്യുന്നു',
    ecosystem: 'IGO ഇക്കോസിസ്റ്റം',
    adminPortal: 'അഡ്മിൻ പോർട്ടൽ',
    deliverTo: 'ഡെലിവറി വിലാസം',
    searchPlaceholder: 'കട്സ്, റെസിപ്പികൾ തിരയുക അല്ലെങ്കിൽ AI-യോട് ചോദിക്കുക...',
    cart: 'കാർട്ട്',
    account: 'അക്കൗണ്ട്',
    member: 'അംഗം',
    expressActive: 'എക്സ്പ്രസ് 30-90 മിനിറ്റ് ഡെലിവറി സജീവം',
    orderFreshCuts: 'ഇപ്പോൾ ഫ്രഷ് കട്സ് ഓർഡർ ചെയ്യുക',
    exploreGymPlans: 'ജിം പ്രോട്ടീൻ പ്ലാനുകൾ കാണുക',
    ordersToday: 'ഇന്ന് ഡെലിവർ ചെയ്ത ഓർഡറുകൾ',
    coldChain: 'കർശന കോൾഡ് ചെയിൻ',
    verifiedReviews: '10,000+ സ്ഥിരീകരിച്ച അവലോകനങ്ങൾ',
    exploreCategories: 'ഫ്രഷ് പ്രോട്ടീൻ മാസ്റ്റർ കാറ്റലോഗ്',
    viewAll: 'എല്ലാം കാണുക',
    flashDeals: 'ഇന്നത്തെ ഫ്ലാഷ് മീറ്റ് ഡീലുകൾ',
    mostPopular: 'ഷെഫുകളും അത്ലറ്റുകളും ഇഷ്ടപ്പെടുന്ന ബെസ്റ്റ് സെല്ലറുകൾ',
    farmToHomeTitle: 'IGO ഫാം-ടു-ഹോം കോൾഡ് ചെയിൻ',
    farmToHomeSub: 'ഞങ്ങൾ ഒരിക്കലും ഫ്രഷ് കട്സ് ഫ്രീസ് ചെയ്യില്ല. തുടർച്ചയായി 0-4°C ചില്ലറിൽ സൂക്ഷിക്കുന്നു.',
    signatureRecipes: 'സിഗ്നേച്ചർ മീറ്റ് റെസിപ്പികൾ',
    exploreRecipes: 'എല്ലാ റെസിപ്പികളും കാണുക',
    subscriptionsTitle: 'പ്രോട്ടീൻ കട്സ് സബ്സ്ക്രിപ്ഷനുകൾ',
    activateSub: 'സബ്സ്ക്രിപ്ഷൻ ആരംഭിക്കുക',
    proteinCalc: 'പ്രോട്ടീൻ ഇൻടേക്ക് കാൽക്കുലേറ്റർ',
    calcSub: 'നിങ്ങളുടെ ദൈനംദിന മാക്രോ പ്രോട്ടീൻ ലക്ഷ്യം കണക്കാക്കി വ്യക്തിഗത മാംസ ശുപാർശകൾ നേടുക',
    calcBtn: 'പ്രോട്ടീൻ ആവശ്യകത അറിയുക',
    igoFamily: 'IGO ഇക്കോസിസ്റ്റം കുടുംബം',
    igoFamilySub: 'ഞങ്ങളുടെ സംയോജിത കൃഷി, കോൾഡ്-ചെയിൻ, മത്സ്യബന്ധനം, എക്സ്പ്രസ് ഡെലിവറി ഗ്രൂപ്പുകൾ പര്യവേക്ഷണം ചെയ്യുക',
    // Footer
    footerTagline: 'ഫാം ഫ്രഷ്, ആരോഗ്യത്തോടെ ഇരിക്കുക',
    customerCare: 'കസ്റ്റമർ കെയർ',
    termsConditions: 'നിബന്ധനകളും വ്യവസ്ഥകളും',
    privacyPolicy: 'സ്വകാര്യതാ നയം',
    shippingPolicy: 'ഷിപ്പിംഗ് നയം',
    returnPolicy: 'റിട്ടേൺ നയം',
    contactUs: 'ഞങ്ങളെ ബന്ധപ്പെടുക',
    accountHeading: 'അക്കൗണ്ട്',
    myAccount: 'എന്റെ അക്കൗണ്ട്',
    cartNav: 'കാർട്ട്',
    wishlist: 'വിഷ്‌ലിസ്റ്റ്',
    productNav: 'ഉൽപ്പന്നം',
    blog: 'ബ്ലോഗ്',
    newsletter: 'ന്യൂസ്‌ലെറ്റർ',
    subscribedMsg: 'സബ്സ്ക്രൈബ് ചെയ്തു! നിങ്ങളുടെ ഇൻബോക്സ് ശ്രദ്ധിക്കുക.',
    emailPlaceholder: 'ഇമെയിൽ',
    subscribe: 'സബ്സ്ക്രൈബ് ചെയ്യുക',
    followUs: 'ഞങ്ങളെ ഫോളോ ചെയ്യുക',
    copyright: 'IGO പ്രോട്ടീൻ കട്സ്. എല്ലാ അവകാശങ്ങളും നിക്ഷിപ്തം.',
    fssaiLic: 'FSSAI ലൈസൻസ്: 10022043000918',
    // Breadcrumbs & common
    home: 'ഹോം',
    addToCart: 'ചേർക്കുക',
    soldOut: 'സ്റ്റോക്ക് തീർന്നു',
    deliveryIn: 'ഡെലിവറി',
    deliveryTime30to90: '30-90 മിനിറ്റിനുള്ളിൽ ഡെലിവറി',
    buyNow: 'ഇപ്പോൾ വാങ്ങുക',
    added: 'ചേർത്തു!',
    notify: 'അറിയിക്കുക',
    notified: 'അറിയിച്ചു!',
    addToBasket: 'ബാസ്ക്കറ്റിൽ ചേർക്കുക',
    outOfStockBanner: 'നിലവിൽ സ്റ്റോക്കിൽ ഇല്ല',
    outOfStockBannerSub: 'ഞങ്ങൾ ഇത് വീണ്ടും സ്റ്റോക്ക് ചെയ്യുന്നു — നിങ്ങളുടെ ഇമെയിൽ നൽകുക, തിരികെ വരുമ്പോൾ ഞങ്ങൾ അറിയിക്കും.',
    notifyMeCta: 'എന്നെ അറിയിക്കുക',
    notifyMeSub: 'സ്റ്റോക്കിൽ വരുമ്പോൾ',
    requestAccepted: 'അഭ്യർത്ഥന സ്വീകരിച്ചു',
    requestAcceptedSub: 'ഈ ഉൽപ്പന്നം ലഭ്യമാകുമ്പോൾ ഞങ്ങൾ നിങ്ങളെ അറിയിക്കും.',
    notifySubmit: 'എന്നെ അറിയിക്കുക',
    notifySubmitting: 'സമർപ്പിക്കുന്നു...',
    notifyCancel: 'റദ്ദാക്കുക',
    notifyErrorGeneric: 'നിങ്ങളുടെ അഭ്യർത്ഥന സമർപ്പിക്കാൻ കഴിഞ്ഞില്ല — അൽപ്പസമയത്തിനുശേഷം വീണ്ടും ശ്രമിക്കുക.',
    close: 'അടയ്ക്കുക',
    // Cart page — step labels, header, empty state, order confirmation
    stepYourCart: 'നിങ്ങളുടെ കാർട്ട്',
    stepDeliveryPayment: 'ഡെലിവറി & പേയ്‌മെന്റ്',
    stepCookingPlan: 'കുക്കിംഗ് പ്ലാൻ',
    stepConfirmed: 'സ്ഥിരീകരിച്ചു',
    continueShopping: 'ഷോപ്പിംഗ് തുടരുക',
    yourCartTitle: 'നിങ്ങളുടെ കാർട്ട്',
    itemsReady: 'ഡെലിവറിക്ക് തയ്യാർ',
    clearCart: 'കാർട്ട് ക്ലിയർ ചെയ്യുക',
    emptyCartTitle: 'നിങ്ങളുടെ കാർട്ട് നിലവിൽ ശൂന്യമാണ്',
    emptyCartSub: 'ഫാം-ഫ്രഷ്, 100% ആന്റിബയോട്ടിക് രഹിത ചിക്കൻ കട്സ്, മൃദുവായ മട്ടൺ, വൈൽഡ്-ക്യാച്ച് സീഫുഡ്, ഫ്രഷ് ഫാം മുട്ടകൾ പര്യവേക്ഷണം ചെയ്യുക.',
    shopFreshChicken: 'ഫ്രഷ് ചിക്കൻ വാങ്ങുക',
    viewHotOffers: 'ഹോട്ട് ഓഫറുകൾ കാണുക',
    orderPlacedTitle: 'ഓർഡർ വിജയകരമായി നൽകി!',
    orderPlacedSub: 'നിങ്ങളുടെ കോൾഡ്-ചെയിൻ ഓർഡർ സ്ഥിരീകരിച്ചു, ഞങ്ങളുടെ മാസ്റ്റർ ബുച്ചർമാർ തയ്യാറാക്കുന്നു.',
    yourOrderNumber: 'നിങ്ങളുടെ ഓർഡർ നമ്പർ',
    orderSummary: 'ഓർഡർ സംഗ്രഹം',
    totalPaid: 'ആകെ അടച്ചത്',
    deliverySlotLabel: 'ഡെലിവറി സ്ലോട്ട്',
    trackThisOrder: 'ഈ ഓർഡർ ട്രാക്ക് ചെയ്യുക',
    viewInMyOrders: 'എന്റെ ഓർഡറുകളിൽ കാണുക',
    orderSavedNote: 'ഈ ഓർഡർ ഇപ്പോൾ നിങ്ങളുടെ അക്കൗണ്ടിൽ സേവ് ചെയ്തിരിക്കുന്നു, നിങ്ങളുടെ പ്രൊഫൈലിലെ എന്റെ ഓർഡറുകളിൽ എപ്പോഴും കാണാം.',
    // Cart Step 2 — address, delivery slot, payment
    deliverToStep: 'ഡെലിവറി വിലാസം',
    noSavedAddress: 'സേവ് ചെയ്ത വിലാസം കണ്ടെത്തിയില്ല.',
    addOneInProfile: 'നിങ്ങളുടെ പ്രൊഫൈലിൽ ഒന്ന് ചേർക്കുക',
    toContinue: 'തുടരാൻ.',
    defaultLabel: 'ഡിഫോൾട്ട്',
    changeLabel: 'മാറ്റുക',
    editLabel: 'എഡിറ്റ് ചെയ്യുക',
    addNewAddress: 'പുതിയ വിലാസം ചേർക്കുക',
    selectDeliverySlot: 'ഡെലിവറി സമയ സ്ലോട്ട് തിരഞ്ഞെടുക്കുക',
    coldChainGuaranteed: 'കോൾഡ് ചെയിൻ ഗ്യാരണ്ടീഡ്',
    slotExpress: '30-മിനിറ്റ് എക്സ്പ്രസ്',
    slotInstantDispatch: 'തൽക്ഷണ ഡിസ്പാച്ച്',
    slotMorning: 'രാവിലെ',
    slotAfternoon: 'ഉച്ചയ്ക്ക്',
    slotEvening: 'വൈകുന്നേരം',
    selectPaymentMethod: 'പേയ്‌മെന്റ് രീതി തിരഞ്ഞെടുക്കുക',
    secure256bit: '256-ബിറ്റ് സുരക്ഷിതം',
    paymentCard: 'കാർഡ്',
    paymentWallet: 'വാലറ്റ്',
    paymentCOD: 'ഡെലിവറി സമയത്ത് പണം',
    redeemWalletPrefix: 'ഈ ഓർഡറിൽ ₹',
    redeemWalletSuffix: ' വരെ IGO വാലറ്റ് ക്രെഡിറ്റും റിഡീം ചെയ്യുക',
    // Cart Step 3 — cooking plan
    cookingPlanQuestion: 'നിങ്ങൾ എന്താണ് പാചകം ചെയ്യാൻ പദ്ധതിയിടുന്നത്?',
    cookingPlanSub: 'ഒരു കുക്കിംഗ് സ്റ്റൈൽ തിരഞ്ഞെടുക്കുക, ഞങ്ങൾ നിങ്ങളുടെ ഓർഡറിനൊപ്പം ഫ്രഷ് പച്ചക്കറികളും മസാലകളും ചേർക്കും.',
    cookBiryani: 'ബിരിയാണി',
    cookCurry: 'കറി / ഗ്രേവി',
    cookFry: 'വറുത്തത് / റോസ്റ്റ്',
    cookKebab: 'കബാബ് / തന്തൂരി',
    // Frequently bought together
    frequentlyBought: 'ഇടയ്ക്കിടെ ഒരുമിച്ച് വാങ്ങുന്നവ',
    frequentlyBoughtSub: 'ഫ്രഷ് പ്രോട്ടീൻ ചേർക്കലുകൾ ഉപയോഗിച്ച് നിങ്ങളുടെ കിച്ചൻ ഓർഡർ പൂർത്തിയാക്കുക.',
    addShort: '+ ചേർക്കുക',
    bulkDiscountPrefix: 'ബൾക്ക് -',
    removeLabel: 'നീക്കം ചെയ്യുക',
    // Order summary sidebar
    itemsTotal: 'ഇനങ്ങളുടെ ആകെത്തുക',
    bulkWholesaleDiscount: 'ബൾക്ക് / മൊത്ത കിഴിവ്',
    vacuumPacking: '0-4°C വാക്വം ജെൽ പാക്ക് പാക്കിംഗ്',
    freeLabel: 'സൗജന്യം',
    expressDeliveryFee: 'എക്സ്പ്രസ് ഡെലിവറി ഫീ',
    taxesGST: 'നികുതികളും GST-യും',
    promoCoupon: 'പ്രോമോ കൂപ്പൺ',
    walletPointsLabel: 'IGO വാലറ്റ് പോയിന്റുകൾ',
    appliedLabel: 'പ്രയോഗിച്ചു',
    searchOffersPlaceholder: 'ഓഫറുകൾ തിരയുക അല്ലെങ്കിൽ കോഡ് നൽകുക',
    applyBtn: 'പ്രയോഗിക്കുക',
    availableOffers: 'ലഭ്യമായ ഓഫറുകൾ',
    totalSavingsPrefix: 'ഈ ഓർഡറിൽ ആകെ ലാഭം: ₹',
    grandPayableTotal: 'ആകെ അടയ്‌ക്കേണ്ട തുക',
    includesTaxes: 'എല്ലാ ബാധകമായ നികുതികളും GST-യും ഉൾപ്പെടുന്നു',
    continueToDelivery: 'ഡെലിവറി & പേയ്‌മെന്റിലേക്ക് തുടരുക',
    continueToCooking: 'കുക്കിംഗ് പ്ലാനിലേക്ക് തുടരുക',
    placeOrderBtn: 'ഓർഡർ ചെയ്യുക',
    placingOrder: 'ഓർഡർ ചെയ്യുന്നു...',
    // Simulated payment modal
    payViaLabel: 'വഴി പണമടയ്ക്കുക',
    paymentSimNote: 'ലൈവ് പേയ്‌മെന്റ് ഗേറ്റ്‌വേ ഇതുവരെ ബന്ധിപ്പിച്ചിട്ടില്ല — ഇത് നിങ്ങളുടെ ഓർഡർ ഒരു ഡെമോ പേയ്‌മെന്റായി സ്ഥിരീകരിക്കുന്നു. യഥാർത്ഥ പണം ഈടാക്കില്ല.',
    amountLabel: 'തുക',
    cancelBtn: 'റദ്ദാക്കുക',
    confirmPayment: 'പേയ്‌മെന്റ് സ്ഥിരീകരിക്കുക',
  },
  te: {
    brandName: 'IGO ప్రోటీన్ కట్స్',
    tagline: 'ఫామ్-ఫ్రెష్, యాంటీబయాటిక్-రహిత ప్రోటీన్',
    taglineSub: '30-90 నిమిషాల్లో డెలివరీ',
    ecosystem: 'IGO ఎకోసిస్టమ్',
    adminPortal: 'అడ్మిన్ పోర్టల్',
    deliverTo: 'డెలివరీ చిరునామా',
    searchPlaceholder: 'కట్స్, వంటకాలు వెతకండి లేదా AI ని అడగండి...',
    cart: 'కార్ట్',
    account: 'ఖాతా',
    member: 'సభ్యుడు',
    expressActive: 'ఎక్స్‌ప్రెస్ 30-90 నిమిషాల డెలివరీ యాక్టివ్',
    orderFreshCuts: 'ఇప్పుడే ఫ్రెష్ కట్స్ ఆర్డర్ చేయండి',
    exploreGymPlans: 'జిమ్ ప్రోటీన్ ప్లాన్‌లు చూడండి',
    ordersToday: 'ఈరోజు డెలివరీ చేసిన ఆర్డర్లు',
    coldChain: 'కఠినమైన కోల్డ్ చైన్',
    verifiedReviews: '10,000+ ధృవీకరించిన సమీక్షలు',
    exploreCategories: 'ఫ్రెష్ ప్రోటీన్ మాస్టర్ కేటలాగ్',
    viewAll: 'అన్నీ చూడండి',
    flashDeals: 'నేటి ఫ్లాష్ మీట్ డీల్స్',
    mostPopular: 'చెఫ్‌లు మరియు అథ్లెట్లు ఇష్టపడే బెస్ట్ సెల్లర్లు',
    farmToHomeTitle: 'IGO ఫామ్-టు-హోమ్ కోల్డ్ చైన్',
    farmToHomeSub: 'మేము మా ఫ్రెష్ కట్స్‌ను ఎప్పుడూ ఫ్రీజ్ చేయము. నిరంతరం 0-4°C చిల్లర్‌లో ఉంచబడుతుంది.',
    signatureRecipes: 'సిగ్నేచర్ మీట్ వంటకాలు',
    exploreRecipes: 'అన్ని వంటకాలు చూడండి',
    subscriptionsTitle: 'ప్రోటీన్ కట్స్ సబ్‌స్క్రిప్షన్లు',
    activateSub: 'సబ్‌స్క్రిప్షన్ ప్రారంభించండి',
    proteinCalc: 'ప్రోటీన్ ఇన్‌టేక్ కాలిక్యులేటర్',
    calcSub: 'మీ రోజువారీ మాక్రో ప్రోటీన్ లక్ష్యాన్ని లెక్కించి వ్యక్తిగత మాంసం సిఫార్సులు పొందండి',
    calcBtn: 'ప్రోటీన్ అవసరాన్ని తెలుసుకోండి',
    igoFamily: 'IGO ఎకోసిస్టమ్ కుటుంబం',
    igoFamilySub: 'మా సమీకృత వ్యవసాయం, కోల్డ్-చైన్, మత్స్య మరియు ఎక్స్‌ప్రెస్ డెలివరీ గ్రూపులను అన్వేషించండి',
    // Footer
    footerTagline: 'ఫామ్ ఫ్రెష్, ఆరోగ్యంగా ఉండండి',
    customerCare: 'కస్టమర్ కేర్',
    termsConditions: 'నిబంధనలు & షరతులు',
    privacyPolicy: 'గోప్యతా విధానం',
    shippingPolicy: 'షిప్పింగ్ విధానం',
    returnPolicy: 'రిటర్న్ విధానం',
    contactUs: 'మమ్మల్ని సంప్రదించండి',
    accountHeading: 'ఖాతా',
    myAccount: 'నా ఖాతా',
    cartNav: 'కార్ట్',
    wishlist: 'విష్‌లిస్ట్',
    productNav: 'ఉత్పత్తి',
    blog: 'బ్లాగ్',
    newsletter: 'న్యూస్‌లెటర్',
    subscribedMsg: 'సబ్‌స్క్రైబ్ అయ్యింది! మీ ఇన్‌బాక్స్ చూడండి.',
    emailPlaceholder: 'ఇమెయిల్',
    subscribe: 'సబ్‌స్క్రైబ్ చేయండి',
    followUs: 'మమ్మల్ని ఫాలో అవ్వండి',
    copyright: 'IGO ప్రోటీన్ కట్స్. అన్ని హక్కులు రిజర్వ్ చేయబడ్డాయి.',
    fssaiLic: 'FSSAI లైసెన్స్: 10022043000918',
    // Breadcrumbs & common
    home: 'హోమ్',
    addToCart: 'జోడించు',
    soldOut: 'స్టాక్ లేదు',
    deliveryIn: 'డెలివరీ',
    deliveryTime30to90: '30-90 నిమిషాల్లో డెలివరీ',
    buyNow: 'ఇప్పుడే కొనండి',
    added: 'జోడించబడింది!',
    notify: 'తెలియజేయండి',
    notified: 'తెలియజేయబడింది!',
    addToBasket: 'బాస్కెట్‌కు జోడించు',
    outOfStockBanner: 'ప్రస్తుతం స్టాక్ లేదు',
    outOfStockBannerSub: 'మేము దీన్ని మళ్లీ స్టాక్ చేస్తున్నాము — మీ ఇమెయిల్ ఇవ్వండి, తిరిగి వచ్చిన వెంటనే తెలియజేస్తాము.',
    notifyMeCta: 'నాకు తెలియజేయండి',
    notifyMeSub: 'తిరిగి స్టాక్‌లో వచ్చినప్పుడు',
    requestAccepted: 'అభ్యర్థన ఆమోదించబడింది',
    requestAcceptedSub: 'ఈ ఉత్పత్తి అందుబాటులోకి వచ్చినప్పుడు మేము మీకు తెలియజేస్తాము.',
    notifySubmit: 'నాకు తెలియజేయండి',
    notifySubmitting: 'సమర్పిస్తోంది...',
    notifyCancel: 'రద్దు చేయి',
    notifyErrorGeneric: 'మీ అభ్యర్థనను సమర్పించలేకపోయాము — దయచేసి కొద్దిసేపటి తర్వాత మళ్లీ ప్రయత్నించండి.',
    close: 'మూసివేయి',
    // Cart page — step labels, header, empty state, order confirmation
    stepYourCart: 'మీ కార్ట్',
    stepDeliveryPayment: 'డెలివరీ & చెల్లింపు',
    stepCookingPlan: 'కుకింగ్ ప్లాన్',
    stepConfirmed: 'ధృవీకరించబడింది',
    continueShopping: 'షాపింగ్ కొనసాగించండి',
    yourCartTitle: 'మీ కార్ట్',
    itemsReady: 'డెలివరీకి సిద్ధంగా ఉంది',
    clearCart: 'కార్ట్ ఖాళీ చేయండి',
    emptyCartTitle: 'మీ కార్ట్ ప్రస్తుతం ఖాళీగా ఉంది',
    emptyCartSub: 'ఫామ్-ఫ్రెష్, 100% యాంటీబయాటిక్-రహిత చికెన్ కట్స్, మృదువైన మటన్, వైల్డ్-క్యాచ్ సీఫుడ్ మరియు ఫ్రెష్ ఫామ్ గుడ్లను అన్వేషించండి.',
    shopFreshChicken: 'ఫ్రెష్ చికెన్ కొనండి',
    viewHotOffers: 'హాట్ ఆఫర్లు చూడండి',
    orderPlacedTitle: 'ఆర్డర్ విజయవంతంగా చేయబడింది!',
    orderPlacedSub: 'మీ కోల్డ్-చైన్ ఆర్డర్ నిర్ధారించబడింది మరియు మా మాస్టర్ బుచర్లు తయారు చేస్తున్నారు.',
    yourOrderNumber: 'మీ ఆర్డర్ నంబర్',
    orderSummary: 'ఆర్డర్ సారాంశం',
    totalPaid: 'మొత్తం చెల్లించినది',
    deliverySlotLabel: 'డెలివరీ స్లాట్',
    trackThisOrder: 'ఈ ఆర్డర్‌ను ట్రాక్ చేయండి',
    viewInMyOrders: 'నా ఆర్డర్లలో చూడండి',
    orderSavedNote: 'ఈ ఆర్డర్ ఇప్పుడు మీ ఖాతాలో సేవ్ చేయబడింది మరియు మీ ప్రొఫైల్‌లో నా ఆర్డర్ల కింద ఎల్లప్పుడూ కనిపిస్తుంది.',
    // Cart Step 2 — address, delivery slot, payment
    deliverToStep: 'డెలివరీ చిరునామా',
    noSavedAddress: 'సేవ్ చేసిన చిరునామా కనుగొనబడలేదు.',
    addOneInProfile: 'మీ ప్రొఫైల్‌లో ఒకటి జోడించండి',
    toContinue: 'కొనసాగించడానికి.',
    defaultLabel: 'డిఫాల్ట్',
    changeLabel: 'మార్చు',
    editLabel: 'సవరించు',
    addNewAddress: 'కొత్త చిరునామా జోడించండి',
    selectDeliverySlot: 'డెలివరీ సమయ స్లాట్‌ను ఎంచుకోండి',
    coldChainGuaranteed: 'కోల్డ్ చైన్ గ్యారెంటీ',
    slotExpress: '30-నిమిషాల ఎక్స్‌ప్రెస్',
    slotInstantDispatch: 'తక్షణ డిస్పాచ్',
    slotMorning: 'ఉదయం',
    slotAfternoon: 'మధ్యాహ్నం',
    slotEvening: 'సాయంత్రం',
    selectPaymentMethod: 'చెల్లింపు విధానాన్ని ఎంచుకోండి',
    secure256bit: '256-బిట్ సురక్షితం',
    paymentCard: 'కార్డ్',
    paymentWallet: 'వాలెట్',
    paymentCOD: 'డెలివరీ సమయంలో నగదు',
    redeemWalletPrefix: 'ఈ ఆర్డర్‌పై ₹',
    redeemWalletSuffix: ' వరకు IGO వాలెట్ క్రెడిట్ కూడా వినియోగించండి',
    // Cart Step 3 — cooking plan
    cookingPlanQuestion: 'మీరు ఏమి వండాలని అనుకుంటున్నారు?',
    cookingPlanSub: 'ఒక కుకింగ్ స్టైల్ ఎంచుకోండి, మేము మీ ఆర్డర్‌తో పాటు ఫ్రెష్ కూరగాయలు మరియు మసాలాలను జతచేస్తాము.',
    cookBiryani: 'బిర్యానీ',
    cookCurry: 'కర్రీ / గ్రేవీ',
    cookFry: 'ఫ్రై / రోస్ట్',
    cookKebab: 'కబాబ్ / తందూరి',
    // Frequently bought together
    frequentlyBought: 'తరచుగా కలిసి కొనేవి',
    frequentlyBoughtSub: 'ఫ్రెష్ ప్రోటీన్ జోడింపులతో మీ కిచెన్ ఆర్డర్‌ను పూర్తి చేయండి.',
    addShort: '+ జోడించు',
    bulkDiscountPrefix: 'బల్క్ -',
    removeLabel: 'తీసివేయి',
    // Order summary sidebar
    itemsTotal: 'వస్తువుల మొత్తం',
    bulkWholesaleDiscount: 'బల్క్ / టోకు తగ్గింపు',
    vacuumPacking: '0-4°C వాక్యూమ్ జెల్ ప్యాక్ ప్యాకింగ్',
    freeLabel: 'ఉచితం',
    expressDeliveryFee: 'ఎక్స్‌ప్రెస్ డెలివరీ ఫీజు',
    taxesGST: 'పన్నులు & GST',
    promoCoupon: 'ప్రోమో కూపన్',
    walletPointsLabel: 'IGO వాలెట్ పాయింట్లు',
    appliedLabel: 'వర్తింపజేయబడింది',
    searchOffersPlaceholder: 'ఆఫర్లు వెతకండి లేదా కోడ్ నమోదు చేయండి',
    applyBtn: 'వర్తింపజేయి',
    availableOffers: 'అందుబాటులో ఉన్న ఆఫర్లు',
    totalSavingsPrefix: 'ఈ ఆర్డర్‌పై మొత్తం పొదుపు: ₹',
    grandPayableTotal: 'చెల్లించవలసిన మొత్తం',
    includesTaxes: 'వర్తించే అన్ని పన్నులు & GST తో సహా',
    continueToDelivery: 'డెలివరీ & చెల్లింపుకు కొనసాగండి',
    continueToCooking: 'కుకింగ్ ప్లాన్‌కు కొనసాగండి',
    placeOrderBtn: 'ఆర్డర్ చేయండి',
    placingOrder: 'ఆర్డర్ చేయబడుతోంది...',
    // Simulated payment modal
    payViaLabel: 'దీని ద్వారా చెల్లించండి',
    paymentSimNote: 'లైవ్ పేమెంట్ గేట్‌వే ఇంకా కనెక్ట్ చేయబడలేదు — ఇది మీ ఆర్డర్‌ను డెమో పేమెంట్‌గా నిర్ధారిస్తుంది. నిజమైన డబ్బు వసూలు చేయబడదు.',
    amountLabel: 'మొత్తం',
    cancelBtn: 'రద్దు చేయి',
    confirmPayment: 'చెల్లింపును నిర్ధారించండి',
  },
  kn: {
    brandName: 'IGO ಪ್ರೋಟೀನ್ ಕಟ್ಸ್',
    tagline: 'ಫಾರ್ಮ್-ಫ್ರೆಶ್, ಆಂಟಿಬಯಾಟಿಕ್-ಮುಕ್ತ ಪ್ರೋಟೀನ್',
    taglineSub: '30-90 ನಿಮಿಷಗಳಲ್ಲಿ ಡೆಲಿವರಿ',
    ecosystem: 'IGO ಇಕೋಸಿಸ್ಟಂ',
    adminPortal: 'ಅಡ್ಮಿನ್ ಪೋರ್ಟಲ್',
    deliverTo: 'ಡೆಲಿವರಿ ವಿಳಾಸ',
    searchPlaceholder: 'ಕಟ್ಸ್, ಪಾಕವಿಧಾನಗಳನ್ನು ಹುಡುಕಿ ಅಥವಾ AI ಅನ್ನು ಕೇಳಿ...',
    cart: 'ಕಾರ್ಟ್',
    account: 'ಖಾತೆ',
    member: 'ಸದಸ್ಯ',
    expressActive: 'ಎಕ್ಸ್‌ಪ್ರೆಸ್ 30-90 ನಿಮಿಷ ಡೆಲಿವರಿ ಸಕ್ರಿಯ',
    orderFreshCuts: 'ಈಗಲೇ ತಾಜಾ ಕಟ್ಸ್ ಆರ್ಡರ್ ಮಾಡಿ',
    exploreGymPlans: 'ಜಿಮ್ ಪ್ರೋಟೀನ್ ಪ್ಲಾನ್‌ಗಳನ್ನು ನೋಡಿ',
    ordersToday: 'ಇಂದು ಡೆಲಿವರ್ ಆದ ಆರ್ಡರ್‌ಗಳು',
    coldChain: 'ಕಠಿಣ ಕೋಲ್ಡ್ ಚೈನ್',
    verifiedReviews: '10,000+ ಪರಿಶೀಲಿತ ವಿಮರ್ಶೆಗಳು',
    exploreCategories: 'ತಾಜಾ ಪ್ರೋಟೀನ್ ಮಾಸ್ಟರ್ ಕ್ಯಾಟಲಾಗ್',
    viewAll: 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ',
    flashDeals: 'ಇಂದಿನ ಫ್ಲ್ಯಾಶ್ ಮೀಟ್ ಡೀಲ್‌ಗಳು',
    mostPopular: 'ಬಾಣಸಿಗರು ಮತ್ತು ಕ್ರೀಡಾಪಟುಗಳು ಇಷ್ಟಪಡುವ ಬೆಸ್ಟ್ ಸೆಲ್ಲರ್‌ಗಳು',
    farmToHomeTitle: 'IGO ಫಾರ್ಮ್-ಟು-ಹೋಮ್ ಕೋಲ್ಡ್ ಚೈನ್',
    farmToHomeSub: 'ನಾವು ನಮ್ಮ ತಾಜಾ ಕಟ್ಸ್‌ಗಳನ್ನು ಎಂದಿಗೂ ಫ್ರೀಜ್ ಮಾಡುವುದಿಲ್ಲ. ನಿರಂತರವಾಗಿ 0-4°C ಚಿಲ್ಲರ್‌ನಲ್ಲಿ ಇಡಲಾಗುತ್ತದೆ.',
    signatureRecipes: 'ಸಿಗ್ನೇಚರ್ ಮೀಟ್ ಪಾಕವಿಧಾನಗಳು',
    exploreRecipes: 'ಎಲ್ಲಾ ಪಾಕವಿಧಾನಗಳನ್ನು ನೋಡಿ',
    subscriptionsTitle: 'ಪ್ರೋಟೀನ್ ಕಟ್ಸ್ ಚಂದಾದಾರಿಕೆಗಳು',
    activateSub: 'ಚಂದಾದಾರಿಕೆ ಪ್ರಾರಂಭಿಸಿ',
    proteinCalc: 'ಪ್ರೋಟೀನ್ ಇನ್‌ಟೇಕ್ ಕ್ಯಾಲ್ಕುಲೇಟರ್',
    calcSub: 'ನಿಮ್ಮ ದೈನಂದಿನ ಮ್ಯಾಕ್ರೋ ಪ್ರೋಟೀನ್ ಗುರಿಯನ್ನು ಲೆಕ್ಕಹಾಕಿ ಮತ್ತು ವೈಯಕ್ತಿಕ ಮಾಂಸ ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಿರಿ',
    calcBtn: 'ಪ್ರೋಟೀನ್ ಅಗತ್ಯವನ್ನು ತಿಳಿಯಿರಿ',
    igoFamily: 'IGO ಇಕೋಸಿಸ್ಟಂ ಕುಟುಂಬ',
    igoFamilySub: 'ನಮ್ಮ ಸಮಗ್ರ ಕೃಷಿ, ಕೋಲ್ಡ್-ಚೈನ್, ಮೀನುಗಾರಿಕೆ ಮತ್ತು ಎಕ್ಸ್‌ಪ್ರೆಸ್ ಡೆಲಿವರಿ ಗುಂಪುಗಳನ್ನು ಅನ್ವೇಷಿಸಿ',
    // Footer
    footerTagline: 'ಫಾರ್ಮ್ ಫ್ರೆಶ್, ಆರೋಗ್ಯವಾಗಿರಿ',
    customerCare: 'ಗ್ರಾಹಕ ಸೇವೆ',
    termsConditions: 'ನಿಯಮಗಳು & ಷರತ್ತುಗಳು',
    privacyPolicy: 'ಗೌಪ್ಯತಾ ನೀತಿ',
    shippingPolicy: 'ಶಿಪ್ಪಿಂಗ್ ನೀತಿ',
    returnPolicy: 'ಹಿಂತಿರುಗಿಸುವ ನೀತಿ',
    contactUs: 'ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ',
    accountHeading: 'ಖಾತೆ',
    myAccount: 'ನನ್ನ ಖಾತೆ',
    cartNav: 'ಕಾರ್ಟ್',
    wishlist: 'ವಿಶ್‌ಲಿಸ್ಟ್',
    productNav: 'ಉತ್ಪನ್ನ',
    blog: 'ಬ್ಲಾಗ್',
    newsletter: 'ನ್ಯೂಸ್‌ಲೆಟರ್',
    subscribedMsg: 'ಚಂದಾದಾರರಾಗಿದ್ದೀರಿ! ನಿಮ್ಮ ಇನ್‌ಬಾಕ್ಸ್ ನೋಡಿ.',
    emailPlaceholder: 'ಇಮೇಲ್',
    subscribe: 'ಚಂದಾದಾರರಾಗಿ',
    followUs: 'ನಮ್ಮನ್ನು ಫಾಲೋ ಮಾಡಿ',
    copyright: 'IGO ಪ್ರೋಟೀನ್ ಕಟ್ಸ್. ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.',
    fssaiLic: 'FSSAI ಲೈಸೆನ್ಸ್: 10022043000918',
    // Breadcrumbs & common
    home: 'ಮುಖಪುಟ',
    addToCart: 'ಸೇರಿಸಿ',
    soldOut: 'ಸ್ಟಾಕ್ ಇಲ್ಲ',
    deliveryIn: 'ಡೆಲಿವರಿ',
    deliveryTime30to90: '30-90 ನಿಮಿಷಗಳಲ್ಲಿ ಡೆಲಿವರಿ',
    buyNow: 'ಈಗಲೇ ಖರೀದಿಸಿ',
    added: 'ಸೇರಿಸಲಾಗಿದೆ!',
    notify: 'ತಿಳಿಸಿ',
    notified: 'ತಿಳಿಸಲಾಗಿದೆ!',
    addToBasket: 'ಬ್ಯಾಸ್ಕೆಟ್‌ಗೆ ಸೇರಿಸಿ',
    outOfStockBanner: 'ಪ್ರಸ್ತುತ ಸ್ಟಾಕ್‌ನಲ್ಲಿ ಇಲ್ಲ',
    outOfStockBannerSub: 'ನಾವು ಇದನ್ನು ಮತ್ತೆ ಸ್ಟಾಕ್ ಮಾಡುತ್ತಿದ್ದೇವೆ — ನಿಮ್ಮ ಇಮೇಲ್ ನೀಡಿ, ಮತ್ತೆ ಲಭ್ಯವಾದ ತಕ್ಷಣ ನಾವು ತಿಳಿಸುತ್ತೇವೆ.',
    notifyMeCta: 'ನನಗೆ ತಿಳಿಸಿ',
    notifyMeSub: 'ಸ್ಟಾಕ್‌ಗೆ ಮರಳಿದಾಗ',
    requestAccepted: 'ವಿನಂತಿ ಸ್ವೀಕರಿಸಲಾಗಿದೆ',
    requestAcceptedSub: 'ಈ ಉತ್ಪನ್ನ ಲಭ್ಯವಾದಾಗ ನಾವು ನಿಮಗೆ ತಿಳಿಸುತ್ತೇವೆ.',
    notifySubmit: 'ನನಗೆ ತಿಳಿಸಿ',
    notifySubmitting: 'ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...',
    notifyCancel: 'ರದ್ದುಗೊಳಿಸಿ',
    notifyErrorGeneric: 'ನಿಮ್ಮ ವಿನಂತಿಯನ್ನು ಸಲ್ಲಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ — ದಯವಿಟ್ಟು ಸ್ವಲ್ಪ ಸಮಯದ ನಂತರ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    close: 'ಮುಚ್ಚಿ',
    // Cart page — step labels, header, empty state, order confirmation
    stepYourCart: 'ನಿಮ್ಮ ಕಾರ್ಟ್',
    stepDeliveryPayment: 'ಡೆಲಿವರಿ & ಪಾವತಿ',
    stepCookingPlan: 'ಅಡುಗೆ ಯೋಜನೆ',
    stepConfirmed: 'ದೃಢೀಕರಿಸಲಾಗಿದೆ',
    continueShopping: 'ಶಾಪಿಂಗ್ ಮುಂದುವರಿಸಿ',
    yourCartTitle: 'ನಿಮ್ಮ ಕಾರ್ಟ್',
    itemsReady: 'ಡೆಲಿವರಿಗೆ ಸಿದ್ಧ',
    clearCart: 'ಕಾರ್ಟ್ ಖಾಲಿ ಮಾಡಿ',
    emptyCartTitle: 'ನಿಮ್ಮ ಕಾರ್ಟ್ ಪ್ರಸ್ತುತ ಖಾಲಿಯಾಗಿದೆ',
    emptyCartSub: 'ಫಾರ್ಮ್-ಫ್ರೆಶ್, 100% ಆಂಟಿಬಯಾಟಿಕ್-ಮುಕ್ತ ಚಿಕನ್ ಕಟ್ಸ್, ಮೃದುವಾದ ಮಟನ್, ವೈಲ್ಡ್-ಕ್ಯಾಚ್ ಸೀಫುಡ್ ಮತ್ತು ತಾಜಾ ಫಾರ್ಮ್ ಮೊಟ್ಟೆಗಳನ್ನು ಅನ್ವೇಷಿಸಿ.',
    shopFreshChicken: 'ತಾಜಾ ಚಿಕನ್ ಖರೀದಿಸಿ',
    viewHotOffers: 'ಹಾಟ್ ಆಫರ್‌ಗಳನ್ನು ನೋಡಿ',
    orderPlacedTitle: 'ಆರ್ಡರ್ ಯಶಸ್ವಿಯಾಗಿ ಇಡಲಾಗಿದೆ!',
    orderPlacedSub: 'ನಿಮ್ಮ ಕೋಲ್ಡ್-ಚೈನ್ ಆರ್ಡರ್ ದೃಢೀಕರಿಸಲಾಗಿದೆ ಮತ್ತು ನಮ್ಮ ಮಾಸ್ಟರ್ ಬುಚರ್‌ಗಳು ಸಿದ್ಧಪಡಿಸುತ್ತಿದ್ದಾರೆ.',
    yourOrderNumber: 'ನಿಮ್ಮ ಆರ್ಡರ್ ಸಂಖ್ಯೆ',
    orderSummary: 'ಆರ್ಡರ್ ಸಾರಾಂಶ',
    totalPaid: 'ಒಟ್ಟು ಪಾವತಿಸಿದ್ದು',
    deliverySlotLabel: 'ಡೆಲಿವರಿ ಸ್ಲಾಟ್',
    trackThisOrder: 'ಈ ಆರ್ಡರ್ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    viewInMyOrders: 'ನನ್ನ ಆರ್ಡರ್‌ಗಳಲ್ಲಿ ನೋಡಿ',
    orderSavedNote: 'ಈ ಆರ್ಡರ್ ಈಗ ನಿಮ್ಮ ಖಾತೆಯಲ್ಲಿ ಉಳಿಸಲಾಗಿದೆ ಮತ್ತು ನಿಮ್ಮ ಪ್ರೊಫೈಲ್‌ನ ನನ್ನ ಆರ್ಡರ್‌ಗಳ ಅಡಿಯಲ್ಲಿ ಯಾವಾಗಲೂ ಕಾಣಿಸುತ್ತದೆ.',
    // Cart Step 2 — address, delivery slot, payment
    deliverToStep: 'ಡೆಲಿವರಿ ವಿಳಾಸ',
    noSavedAddress: 'ಉಳಿಸಿದ ವಿಳಾಸ ಕಂಡುಬಂದಿಲ್ಲ.',
    addOneInProfile: 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್‌ನಲ್ಲಿ ಒಂದನ್ನು ಸೇರಿಸಿ',
    toContinue: 'ಮುಂದುವರಿಸಲು.',
    defaultLabel: 'ಡೀಫಾಲ್ಟ್',
    changeLabel: 'ಬದಲಾಯಿಸಿ',
    editLabel: 'ಸಂಪಾದಿಸಿ',
    addNewAddress: 'ಹೊಸ ವಿಳಾಸ ಸೇರಿಸಿ',
    selectDeliverySlot: 'ಡೆಲಿವರಿ ಸಮಯ ಸ್ಲಾಟ್ ಆಯ್ಕೆಮಾಡಿ',
    coldChainGuaranteed: 'ಕೋಲ್ಡ್ ಚೈನ್ ಖಾತರಿ',
    slotExpress: '30-ನಿಮಿಷ ಎಕ್ಸ್‌ಪ್ರೆಸ್',
    slotInstantDispatch: 'ತಕ್ಷಣದ ಡಿಸ್ಪ್ಯಾಚ್',
    slotMorning: 'ಬೆಳಿಗ್ಗೆ',
    slotAfternoon: 'ಮಧ್ಯಾಹ್ನ',
    slotEvening: 'ಸಂಜೆ',
    selectPaymentMethod: 'ಪಾವತಿ ವಿಧಾನವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    secure256bit: '256-ಬಿಟ್ ಸುರಕ್ಷಿತ',
    paymentCard: 'ಕಾರ್ಡ್',
    paymentWallet: 'ವಾಲೆಟ್',
    paymentCOD: 'ಡೆಲಿವರಿ ಸಮಯದಲ್ಲಿ ನಗದು',
    redeemWalletPrefix: 'ಈ ಆರ್ಡರ್‌ನಲ್ಲಿ ₹',
    redeemWalletSuffix: ' ವರೆಗೆ IGO ವಾಲೆಟ್ ಕ್ರೆಡಿಟ್ ಅನ್ನೂ ಬಳಸಿಕೊಳ್ಳಿ',
    // Cart Step 3 — cooking plan
    cookingPlanQuestion: 'ನೀವು ಏನು ಅಡುಗೆ ಮಾಡಲು ಯೋಜಿಸುತ್ತಿದ್ದೀರಿ?',
    cookingPlanSub: 'ಒಂದು ಅಡುಗೆ ಶೈಲಿಯನ್ನು ಆಯ್ಕೆಮಾಡಿ, ನಾವು ನಿಮ್ಮ ಆರ್ಡರ್‌ಗೆ ತಾಜಾ ತರಕಾರಿಗಳು ಮತ್ತು ಮಸಾಲೆಗಳನ್ನು ಹೊಂದಿಸುತ್ತೇವೆ.',
    cookBiryani: 'ಬಿರಿಯಾನಿ',
    cookCurry: 'ಕರಿ / ಗ್ರೇವಿ',
    cookFry: 'ಫ್ರೈ / ರೋಸ್ಟ್',
    cookKebab: 'ಕಬಾಬ್ / ತಂದೂರಿ',
    // Frequently bought together
    frequentlyBought: 'ಆಗಾಗ್ಗೆ ಒಟ್ಟಿಗೆ ಖರೀದಿಸುವಂತಹವು',
    frequentlyBoughtSub: 'ತಾಜಾ ಪ್ರೋಟೀನ್ ಸೇರ್ಪಡೆಗಳೊಂದಿಗೆ ನಿಮ್ಮ ಅಡುಗೆಮನೆ ಆರ್ಡರ್ ಪೂರ್ಣಗೊಳಿಸಿ.',
    addShort: '+ ಸೇರಿಸಿ',
    bulkDiscountPrefix: 'ಬಲ್ಕ್ -',
    removeLabel: 'ತೆಗೆದುಹಾಕಿ',
    // Order summary sidebar
    itemsTotal: 'ವಸ್ತುಗಳ ಒಟ್ಟು',
    bulkWholesaleDiscount: 'ಬಲ್ಕ್ / ಸಗಟು ರಿಯಾಯಿತಿ',
    vacuumPacking: '0-4°C ವ್ಯಾಕ್ಯೂಮ್ ಜೆಲ್ ಪ್ಯಾಕ್ ಪ್ಯಾಕಿಂಗ್',
    freeLabel: 'ಉಚಿತ',
    expressDeliveryFee: 'ಎಕ್ಸ್‌ಪ್ರೆಸ್ ಡೆಲಿವರಿ ಶುಲ್ಕ',
    taxesGST: 'ತೆರಿಗೆಗಳು & GST',
    promoCoupon: 'ಪ್ರೋಮೋ ಕೂಪನ್',
    walletPointsLabel: 'IGO ವಾಲೆಟ್ ಪಾಯಿಂಟ್‌ಗಳು',
    appliedLabel: 'ಅನ್ವಯಿಸಲಾಗಿದೆ',
    searchOffersPlaceholder: 'ಆಫರ್‌ಗಳನ್ನು ಹುಡುಕಿ ಅಥವಾ ಕೋಡ್ ನಮೂದಿಸಿ',
    applyBtn: 'ಅನ್ವಯಿಸಿ',
    availableOffers: 'ಲಭ್ಯವಿರುವ ಆಫರ್‌ಗಳು',
    totalSavingsPrefix: 'ಈ ಆರ್ಡರ್‌ನಲ್ಲಿ ಒಟ್ಟು ಉಳಿತಾಯ: ₹',
    grandPayableTotal: 'ಒಟ್ಟು ಪಾವತಿಸಬೇಕಾದ ಮೊತ್ತ',
    includesTaxes: 'ಎಲ್ಲಾ ಅನ್ವಯಿಸುವ ತೆರಿಗೆಗಳು & GST ಸೇರಿದಂತೆ',
    continueToDelivery: 'ಡೆಲಿವರಿ & ಪಾವತಿಗೆ ಮುಂದುವರಿಸಿ',
    continueToCooking: 'ಅಡುಗೆ ಯೋಜನೆಗೆ ಮುಂದುವರಿಸಿ',
    placeOrderBtn: 'ಆರ್ಡರ್ ಮಾಡಿ',
    placingOrder: 'ಆರ್ಡರ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
    // Simulated payment modal
    payViaLabel: 'ಮೂಲಕ ಪಾವತಿಸಿ',
    paymentSimNote: 'ಲೈವ್ ಪೇಮೆಂಟ್ ಗೇಟ್‌ವೇ ಇನ್ನೂ ಸಂಪರ್ಕಿಸಲಾಗಿಲ್ಲ — ಇದು ನಿಮ್ಮ ಆರ್ಡರ್ ಅನ್ನು ಡೆಮೊ ಪಾವತಿಯಾಗಿ ದೃಢೀಕರಿಸುತ್ತದೆ. ನಿಜವಾದ ಹಣ ಶುಲ್ಕ ವಿಧಿಸಲಾಗುವುದಿಲ್ಲ.',
    amountLabel: 'ಮೊತ್ತ',
    cancelBtn: 'ರದ್ದುಗೊಳಿಸಿ',
    confirmPayment: 'ಪಾವತಿಯನ್ನು ದೃಢೀಕರಿಸಿ',
  }
};

// Previously `lang` only ever reached the Navbar (passed as a direct prop
// from App.tsx) — every other page and component had no way to read the
// selected language, so toggling to Tamil only ever changed the header and
// left the rest of the site in English. This context makes `lang` and a
// `t(key)` helper available anywhere in the tree without prop-drilling
// through 25+ page components.
interface LanguageContextValue {
  lang: Language;
  t: (key: string) => string;
}

const translate = (lang: Language, key: string): string =>
  TRANSLATIONS[lang]?.[key] ?? TRANSLATIONS.en[key] ?? key;

export const LanguageContext = createContext<LanguageContextValue>({
  lang: 'en',
  t: (key: string) => translate('en', key)
});

export const useLang = () => useContext(LanguageContext);
export { translate };

// Shared helper for the many inline (non-t()-keyed) strings across pages —
// same idea as `translate()`/TRANSLATIONS but for one-off content that isn't
// worth adding a dictionary key for. Falls back to English for any language
// missing a given variant, same fallback contract as translate().
export const pick = (
  lang: Language,
  strs: { en: string; ta?: string; hi?: string; ml?: string; te?: string; kn?: string }
): string => strs[lang] ?? strs.en;
