export type Language = 'en' | 'ta';

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    brandName: 'IGO PROTEIN CUTS',
    tagline: 'Farm-Fresh, Antibiotic-Free Protein',
    taglineSub: 'Delivered in 30 Minutes',
    ecosystem: 'IGO ECOSYSTEM',
    adminPortal: 'Admin Portal',
    deliverTo: 'Deliver to',
    searchPlaceholder: 'Search cuts, recipes or ask AI...',
    cart: 'CART',
    account: 'Account',
    member: 'Member',
    expressActive: 'EXPRESS 30-MIN DELIVERY ACTIVE',
    orderFreshCuts: 'Order Fresh Cuts Now',
    exploreGymPlans: 'Explore Gym Protein Plans',
    ordersToday: 'Orders Delivered Today',
    coldChain: 'Strict Cold Chain',
    verifiedReviews: '10,000+ Verified Reviews',
    exploreCategories: 'Fresh Protein Master Catalog',
    viewAll: 'View All',
    flashDeals: "Today's Flash Meat Deals",
    mostPopular: 'Best Sellers Loved by Chefs & Athletes',
    farmToHomeTitle: 'The IGO Farm-To-Home Cold Chain',
    farmToHomeSub: 'We never freeze our fresh cuts. Kept in 0-4°C chillers continuously.',
    signatureRecipes: 'Signature Meat Recipes',
    exploreRecipes: 'Explore All Recipes',
    subscriptionsTitle: 'Protein Cuts Subscriptions',
    activateSub: 'Activate Subscription',
    proteinCalc: 'Protein Intake Calculator',
    calcSub: 'Calculate your daily macro protein target & get personalized meat recommendations',
    calcBtn: 'Calculate Protein Needs',
    igoFamily: 'IGO Ecosystem Family',
    igoFamilySub: 'Explore our integrated agro, cold-chain, fisheries, and express delivery groups',
  },
  ta: {
    brandName: 'IGO புரோட்டீன் கட்ஸ்',
    tagline: 'பண்ணை நன்னீர் & ஆர்கானிக் புரதம்',
    taglineSub: '30 நிமிடங்களில் உங்கள் இல்லத்தில்',
    ecosystem: 'IGO ஈகோசிஸ்டம்',
    adminPortal: 'நிர்வாகி போர்ட்டல்',
    deliverTo: 'டெலிவரி இடம்',
    searchPlaceholder: 'கட்ஸ், சமையல் குறிப்புகள் தேடுங்கள்...',
    cart: 'கார்ட்',
    account: 'கணக்கு',
    member: 'உறுப்பினர்',
    expressActive: '30 நிமிட விரைவு டெலிவரி இயங்குகிறது',
    orderFreshCuts: 'இப்பொழுதே ஆர்டர் செய்க',
    exploreGymPlans: 'ஜிம் புரோட்டீன் திட்டங்கள்',
    ordersToday: 'இன்று டெலிவரி செய்யப்பட்டவை',
    coldChain: '0-4°C சளி சங்கிலி',
    verifiedReviews: '10,000+ சான்றளிக்கப்பட்ட மதிப்புரைகள்',
    exploreCategories: 'புதிய புரதப் பொருட்கள் வரிசை',
    viewAll: 'அனைத்தையும் காண்க',
    flashDeals: 'இன்றைய சிறப்பு தள்ளுபடி சலுகைகள்',
    mostPopular: 'அதிகம் விரும்பப்படும் புதிய கட்ஸ்',
    farmToHomeTitle: 'IGO பண்ணையிலிருந்து வீடு வரை குளிர் சங்கிலி',
    farmToHomeSub: 'நாங்கள் ஒருபோதும் இறைச்சியை உறைவிப்பதில்லை. 0-4°C குளிர்ச்சியில் பாதுகாக்கப்படுகிறது.',
    signatureRecipes: 'பிரத்யேக இறைச்சி சமையல் குறிப்புகள்',
    exploreRecipes: 'அனைத்து சமையல் குறிப்புகள்',
    subscriptionsTitle: 'புரோட்டீன் கட்ஸ் சந்தா திட்டங்கள்',
    activateSub: 'சந்தாவைத் தொடங்குங்கள்',
    proteinCalc: 'புரதத் தேவை கணக்கீடு',
    calcSub: 'உங்கள் தினசரி புரத இலக்கைக் கணக்கிட்டு பரிந்துரைக்கப்படும் கட்ஸ்களைப் பெறுங்கள்',
    calcBtn: 'புரதத் தேவையைத் தெரிந்துகொள்க',
    igoFamily: 'IGO குழுமத்தின் துணை நிறுவனங்கள்',
    igoFamilySub: 'பண்ணை, குளிர் சங்கிலி, மீன்வளம் மற்றும் விரைவு விநியோக சேவைகளை ஆராயுங்கள்',
  }
};
