-- Which of the 83 website SKUs are missing from public.products?
-- Read-only. Creates nothing, changes nothing.
with website_catalog(name) as (values
  ('Anchovy'),
  ('Avocado'),
  ('Beef Cubes'),
  ('Beef Curry Cut'),
  ('Beef Liver'),
  ('Beef Mince'),
  ('Beef Shank'),
  ('Bell Peppers'),
  ('Boneless Goat Mutton (Rich Protein)'),
  ('Broccoli'),
  ('Chef Peri Peri Marinated Chicken Wings'),
  ('Cherry Tomato'),
  ('Chicken 65 (Marinated)'),
  ('Chicken Biryani Kit'),
  ('Chicken Breakfast Sausages'),
  ('Chicken Breast Boneless'),
  ('Chicken Drumsticks'),
  ('Chicken Ham'),
  ('Chicken Leg Piece'),
  ('Chicken Liver'),
  ('Chicken Lollipop Cuts'),
  ('Chicken Mince'),
  ('Chicken Salami'),
  ('Chicken Thigh Boneless'),
  ('Chicken Wings'),
  ('Country Chicken (Naattu Kozhi)'),
  ('Country Chicken (Nattu Kozhi) - Curry Cut'),
  ('Crab'),
  ('Cucumber'),
  ('Duck Eggs'),
  ('Egg Biryani Kit'),
  ('Egg White Pack'),
  ('Farm Fresh Eggs'),
  ('Farm Fresh Quail (Whole Cleaned)'),
  ('Farm Fresh White Eggs (Pack of 12)'),
  ('Festival Combo'),
  ('Fish Amritsari (Marinated Fish Fry)'),
  ('Fresh Farm Chicken - Curry Cut (Skinless)'),
  ('Fresh Mud Crab (Live Caught)'),
  ('Fresh Seer Fish / Vanjaram Steak'),
  ('Fresh Tiger Prawns - Cleaned & Deveined'),
  ('Freshwater Rohu / Katla - Curry Cut'),
  ('Frozen Chicken Nuggets'),
  ('Frozen Chicken Seekh Kebabs'),
  ('Frozen Fish Fillets'),
  ('Frozen Green Peas'),
  ('Goat Mutton Ribs & Chops'),
  ('High Protein Gym Bro Bundle'),
  ('Juicy Chicken Drumsticks (Leg Pieces)'),
  ('Live Mud Crab (Whole, Uncleaned)'),
  ('Mackerel'),
  ('Mutton Biryani Kit'),
  ('Mutton Boneless'),
  ('Mutton Chops'),
  ('Mutton Curry'),
  ('Mutton Leg'),
  ('Mutton Liver'),
  ('Mutton Mince'),
  ('Mutton Ribs'),
  ('Mutton Seekh Kebab (Marinated)'),
  ('Mutton Soup Bones'),
  ('Norwegian Salmon Fillet (Boneless)'),
  ('Organic Brown Country Hen Eggs (Pack of 6)'),
  ('Prawns'),
  ('Premium Goat Mutton - Curry Cut'),
  ('Quail Eggs'),
  ('Ribeye Steak'),
  ('Rohu Fish'),
  ('Salmon Fillet'),
  ('Sardines'),
  ('Seafood Combo'),
  ('Sirloin Steak'),
  ('Squid'),
  ('Sun-Dried Anchovy (Nethili Karuvadu)'),
  ('Sunday Family Feast Combo'),
  ('T-Bone Steak'),
  ('Tandoori Chicken Tikka (Boneless Marinated)'),
  ('Tender Chicken Breast - Boneless'),
  ('Tenderloin Steak'),
  ('Tuna Steak'),
  ('Turkey Bacon'),
  ('Weekly Fitness Protein Pass'),
  ('Whole Chicken')
)
select w.name as missing_product
from website_catalog w
left join public.products p on lower(trim(p.name)) = lower(trim(w.name))
where p.id is null
order by w.name;
